language: cpp

install:
 - gem install coveralls-lcov

addons:
  apt:
    packages:
    - libsfml-dev
    - lcov

script:
 - scripts/build.sh && scripts/test.sh

after_success:
 - coveralls-lcov build/game_coverage.info.cleaned
