language: cpp

install:
 - gem install coveralls-lcov

addons:
  apt:
    packages:
    - libsfml-dev
    - lcov

script:
 - scripts/build.sh && scripts/test.sh

after_success:
 - coveralls --gcov-options '\-lp' -e '/usr/*' -e '*gtest/*'
 - coveralls-lcov build/game_coverage.info
