language: cpp

before_install:
  - pip install --user cpp-coveralls

addons:
  apt:
    packages:
    - libsfml-dev

script:
 - scripts/build.sh && scripts/test.sh

after_success:
 - coveralls --gcov-options '\-lp'
